using System;
using System.Collections.Generic;
using System.Text;

namespace CanyonShooter.GameClasses
{
    public enum Crosshair
    {
        MINIGUN_CROSSHAIR_READY,
        MINIGUN_CROSSHAIR_TARGET,
        MINIGUN_CROSSHAIR_HOT, 
        MINIGUN_CROSSHAIR_BLOCKED,
        ROKET_CROSSHAIR_READY,
        ROKET_CROSSHAIR_TARGET,
        ROKET_CROSSHAIR_HOT,
        ROKET_CROSSHAIR_BLOCKED, 
        PLASMA_CROSSHAIR_READY,
        PLASMA_CROSSHAIR_TARGET,
        PLASMA_CROSSHAIR_HOT,
        PLASMA_CROSSHAIR_BLOCKED,
        PHASER_CROSSHAIR_READY,
        PHASER_CROSSHAIR_TARGET, 
        PHASER_CROSSHAIR_HOT,
        PHASER_CROSSHAIR_BLOCKED,
        GODMODE_CROSSHAIR_READY,
        GODMODE_CROSSHAIR_TARGET,
        GODMODE_CROSSHAIR_HOT,
        GODMODE_CROSSHAIR_BLOCKED
    }
}
